### Get all students
GET http://localhost:5044/api/Student
Accept: application/json

### Get student by id
GET http://localhost:5044/api/Student/1
Accept: application/json

###Get student by name
GET http://localhost:5044/api/Student/Name/Paco
Accept: application/json

###Post Student

POST http://localhost:5044/api/Student
Content-Type: application/json

{
    "id": 1 ,
    "name": "Pepe",
    "surname": "string",
    "email": "string",
    "phoneNumber": 0,
    "isTutor": false,
    "language": "string"
}

###Put Student
PUT http://localhost:5044/api/Student/1
Content-Type: application/json

{
    "id": 4,
    "name": "José",
    "surname": "string",
    "email": "string",
    "phoneNumber": 0,
    "isTutor": true,
    "language": "string"
}

###Delete Student
DELETE http://localhost:5044/api/Student/1
Accept: application/json
###Get all moderators
GET http://localhost:5044/api/Moderator
Accept: application/json
###Post Moderator
POST http://localhost:5044/api/Moderator
Content-Type: application/json

{
    "id": 1,
    "name": "John",
    "surname": "Doe",
    "email": "johndoe@example.com",
    "phoneNumber": 123456789,
    "accessLevel": "Senior",
    "assignedSections": ["Reviews", "Subjects"],
    "bannedReviews": []
}

###Get moderator by id
GET http://localhost:5044/api/Moderator/1
Accept: application/json

### Assign a section to a moderator
PUT http://localhost:5044/api/Moderator/1/assignSection
Content-Type: application/json

"Materials"
###Delete Moderator
DELETE http://localhost:5044/api/Moderator/1
Accept: application/json
